---
namespace: "tcharl"
name: "Iam"
version: "2.0.1"
description: "Deploys Keycloak on bare metal"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible-iam"
documentation: "https://github.com/OsgiliathEnterprise/ansible-iam/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/ansible-iam"
issues: "https://github.com/OsgiliathEnterprise/ansible-iam/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "keycloak"
